"""
search_docs.py

Purpose:
--------
Tool to search documents using a two-stage RAG retriever (FAISS + FlashRank).
Automatically scopes search to the current user's isolated index.
"""

from typing import Annotated
from langchain_core.tools import StructuredTool
from langgraph.prebuilt import InjectedState
from pydantic import BaseModel, Field

from app.vectorstore.retriever import retrieve_docs


class SearchDocsInput(BaseModel):
    """
    Input schema for search_docs tool.
    The query is provided by the LLM. 
    The user_id is injected automatically from the graph state.
    """
    query: str = Field(..., description="Search query to find relevant financial documents or transactions")


async def search_docs(
    query: str, 
    state: Annotated[dict, InjectedState]
) -> str:
    """
    Search documents and return relevant context.
    
    Args:
        query (str): The search query generated by the LLM.
        state (dict): The current graph state, used to pull 'user_id'.

    Returns:
        str: Reranked document content for the LLM to use as context.
    """
    # Extract user_id from injected state
    user_id = state.get("user_id")
    
    if not user_id:
        return "Error: No user_id found in session. Cannot search documents."

    # Retrieve and rerank (now async)
    docs = await retrieve_docs(user_id, query)

    if not docs:
        return "No relevant documents found for your query in the database."

    # Combine top results with source indicators
    context_parts = []
    for i, doc in enumerate(docs):
        context_parts.append(f"Source {i+1}:\n{doc.page_content}")

    return "\n\n".join(context_parts)


# Tool wrapper
# NOTE: must use coroutine= (not func=) because search_docs is async.
# Using func= with an async function means ToolNode never awaits it —
# the tool returns a raw coroutine object, the LLM sees garbage output,
# retries the tool call endlessly, and hits the recursion limit.
search_docs_tool = StructuredTool.from_function(
    coroutine=search_docs,
    name="search_docs",
    description="Search the user's uploaded financial documents (PDFs, CSV uploads, reports, statements, invoices). Use this for unstructured file content, not for live transaction counts or summary metrics.",
    args_schema=SearchDocsInput,
)